# Generated by Django 5.2.7 on 2025-10-22 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Cake', 'Cake'), ('Soft Drink', 'Soft Drink')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('campus', models.CharField(choices=[('Ebene', 'Ebene')], max_length=50)),
                ('join_in', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_inserted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.product')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.student')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes_200', models.PositiveIntegerField(default=0)),
                ('notes_100', models.PositiveIntegerField(default=0)),
                ('notes_50', models.PositiveIntegerField(default=0)),
                ('notes_25', models.PositiveIntegerField(default=0)),
                ('coins_20', models.PositiveIntegerField(default=0)),
                ('coins_10', models.PositiveIntegerField(default=0)),
                ('coins_5', models.PositiveIntegerField(default=0)),
                ('coins_1', models.PositiveIntegerField(default=0)),
                ('total_return', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('denominations', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.student')),
            ],
        ),
        migrations.CreateModel(
            name='AmountInserted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes_200', models.PositiveIntegerField(default=0)),
                ('notes_100', models.PositiveIntegerField(default=0)),
                ('notes_50', models.PositiveIntegerField(default=0)),
                ('notes_25', models.PositiveIntegerField(default=0)),
                ('coins_20', models.PositiveIntegerField(default=0)),
                ('coins_10', models.PositiveIntegerField(default=0)),
                ('coins_5', models.PositiveIntegerField(default=0)),
                ('coins_1', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('denominations', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.student')),
            ],
        ),
    ]
