# Generated by Django 5.2.7 on 2025-10-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='change_return',
            new_name='change_amount',
        ),
    ]
