# Generated by Django 5.2.7 on 2025-10-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_rename_change_return_order_change_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student',
        ),
    ]
